### ISSUE TITLE
Blocklist requests

### ISSUE THREAD

**Issue by zebvv** [AnAClearMind/A-n-A-ClearMind#1]
chaturbate.com
chaturbate.eu
camvirt.com

**Comment by RemusDBD** [comment]
![AnAClearMind-issues-1](https://github.com/user-attachments/assets/a2f1edf4-d5cc-432f-947a-54f5a624a02f)

Hi @zebvv ,

In the plugin popup, you can insert the domain you may want to block.

**Comment by zebvv** [comment]
im on mobile (Firefox for Android V. 133.0
2)
the pop-up for adding new websites doesn't work

![Screenshot_2024-12-08-07-53-51-456_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/2a564e40-4d11-4d51-b879-c47ab9ef5bf8)

the options to add something to the blocklist are not available

**Comment by AnAClearMind** [comment]
> the options to add something to the blocklist are not available

Hello, @zebvv.
Just checked and can confirm this is a bug. We will fix it and roll out an update ASAP.

**Comment by AnAClearMind** [comment]
@zebvv we have published a new version [1.1.8] in Firefox store where this issue has been resolved. Please reinstall the extension in your mobile browser. 

Also, added the above suggested sites instead of lesser known ones to the default blocklist. 

Thank you for helping us to find this bug in German localization files.
